---

- hosts: all
  become: no
  gather_facts: no
  tasks:
  - git: https://github.com/john-deng/install-docker-on-centos.git dest=/root/install-docker-on-centos refspec=+refs/pull/*:refs/heads/*
  - script: /root/install-centos-server/install-docker-on-centos.sh