---

- include: fetch-scripts.yml

- hosts: all
  become: no
  gather_facts: no
  tasks:
  - name: install common tools
    shell: ./install-common-tools.sh chdir=/root/install
  - name: install docker
    shell: ./install-docker-on-centos.sh all storage=sdb chdir=/root/install
 
