kind: "List"
apiVersion: "v1"
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: jenkins-storage
    labels:
      provider: "openshift"
      group: "io.openshift.devops.apps"
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /exports/jenkins
      server: 172.22.0.1

