apiVersion: v1
kind: Service
metadata:
  name: registry-console
  namespace: default
  selfLink: /api/v1/namespaces/default/services/registry-console
  uid: 1d4c833f-aba9-11e6-8fe7-005056345498
  resourceVersion: '1265'
  creationTimestamp: '2016-11-16T03:02:31Z'
  labels:
    app: registry-console
    createdBy: registry-console-template
    name: registry-console
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  ports:
    - name: registry-console
      protocol: TCP
      port: 9000
      targetPort: 9090
  selector:
    name: registry-console
  clusterIP: 172.30.12.244
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}

